### ISSUE TITLE
Snow grass looks out of place

### ISSUE THREAD

**Issue by craftyfox89** [foreverphoenix/the-phoenix-flavour#100]
Snow grass from Cathedral Landscapes looks amazing by itself but can look out of place in comparison to the surrounding objects. Have only tested around Riverwood but it can be really bothering - the contrast is harsh and it is unrealistic. Does it make sense to have grass on snowy surfaces?

![enb2021_2_4_18_33_36](https://user-images.githubusercontent.com/51448087/106938667-9700ef00-671f-11eb-9734-bbcaeb9cc617.png)

Could be replaced with another less 'in the face' variant of grass or even removed? There is a mod that specifically removes snow grass: 'Disable Snow Grass - For Vanilla and Cathedral Landscapes' (https://www.nexusmods.com/skyrimspecialedition/mods/36974).

**Comment by foreverphoenix** [comment]
We switched to Veydosebrom as our grass overhaul.
