### ISSUE TITLE
Shiny dirt on the bridges.

### ISSUE THREAD

**Issue by Kravarnik** [foreverphoenix/the-phoenix-flavour#103]
Screenshot below explains it all. This has been an issue from the 3.0 version. The nif files affecting the bridge come from "Landscapes - Cathedral Concept", but the issue also appears on SMIM.

![image](https://user-images.githubusercontent.com/21342211/107146532-a4052480-6951-11eb-8c83-e0492cfffea2.png)

**Comment by Kravarnik** [comment]
Possible workaround until Phoenix updates the guide (Credits to Delta from TPF Discord):

You can download [Blended Roads](https://www.nexusmods.com/skyrimspecialedition/mods/8834).
During installation check those options:

![image](https://user-images.githubusercontent.com/21342211/107151181-e5a1c980-6969-11eb-97f6-39ee241c8eef.png)

Once the mod is installed, move it below "Landscapes - Cathedral Concept" and hide/remove the .esp:

![image](https://user-images.githubusercontent.com/21342211/107151220-1550d180-696a-11eb-858b-477564aeae16.png)

Result:

![image](https://user-images.githubusercontent.com/21342211/107151099-86dc5000-6969-11eb-8232-3114800ecca2.png)

**Comment by foreverphoenix** [comment]
Yup, the version of Blended Roads in Cath Landscapes is outdated. The mod will be added manually in the next release of TPF. Thanks!
