### ISSUE TITLE
The new Khajiit and Argonian Vampire NPCs added by Diverse Skyrim need their FaceGeom updated to work with Beast Race Vampire Fang Removal

### ISSUE THREAD

**Issue by duskyBabz** [foreverphoenix/the-phoenix-flavour#112]
I'm sure you know exactly how to do this so I won't bother explaining. There's 10 NPCs total, 5 of each race, and you don't need the FaceTint files since they're exactly the same

On another note, regarding the EFM white teeth thing, can't you just have people tweak the texture in paint.net? Even a simple image-wide brightness reduction and tint shift would do the trick nicely and it's idiot-proof

On yet another note, if the only issue with the version of Blended Roads included in Cath. Landscapes is the bridges, you might as well use the optional addon "Medieval Bridges" instead of the full Blended Roads main file. Would reduce file redundancy and the bridges look much better imo

There's also a new update file for LeanWolf's Better-Shaped Weapons that fixes something with the Orcish greatsword. Says it's only needed if you use the version with sheath, which I believe we do

**Comment by foreverphoenix** [comment]
> I'm sure you know exactly how to do this so I won't bother explaining. There's 10 NPCs total, 5 of each race, and you don't need the FaceTint files since they're exactly the same

Completely missed that lol since there are no Khajiit or Argonian vampires in vanilla. Thanks for the heads up!

> On another note, regarding the EFM white teeth thing, can't you just have people tweak the texture in paint.net? Even a simple image-wide brightness reduction and tint shift would do the trick nicely and it's idiot-proof

Good point. I don't know how to properly do that unfortunately but maybe someone else will pitch in. =)

> On yet another note, if the only issue with the version of Blended Roads included in Cath. Landscapes is the bridges, you might as well use the optional addon "Medieval Bridges" instead of the full Blended Roads main file. Would reduce file redundancy and the bridges look much better imo

Thanks! Done in 4.1.

> There's also a new update file for LeanWolf's Better-Shaped Weapons that fixes something with the Orcish greatsword. Says it's only needed if you use the version with sheath, which I believe we do

And also added in 4.1 =)

**Comment by foreverphoenix** [comment]
In 4.2 EFM was yeeted and facegen is now a DIY thing so everything is fixed. =)
