### ISSUE TITLE
Buyable golden claw

### ISSUE THREAD

**Issue by Dargor21** [foreverphoenix/the-phoenix-flavour#124]
4.1: Increased buy price for the Golden Claw from 500 to 5000 Septims
I can buy it with only 2800 septims on me and it removes 500.
I did a little test in game price depends on the player level:
lvl - price
6 - 500
10 - 750
20 - 1000
30 - 1250
40+ - 1500

**Comment by foreverphoenix** [comment]
Fixed in 4.2, I missed that the script wasn't actually referencing the global in the plugin.
