### ISSUE TITLE
Mara Quest Text Mismatch

### ISSUE THREAD

**Issue by Soobrakay** [foreverphoenix/the-phoenix-flavour#125]
Wabbajack build downloaded February 13, 2021.
Version: 4.1 or 4.1.1 based on the dates in the Changelog.

Issue: Harder Mara Quests from Andrealphus' Gameplay Tweaks says it upped the number of pamphlets to 30. The quest text says 20. Quest requires 30. 

The Phoenix Flavour Changelog says the Conflict Resolution Patch for 4.1 dropped the number of pamphlets back down to 20. Looks like it only affected the text, not the actual quest conditions.

**Comment by Soobrakay** [comment]
![image](https://user-images.githubusercontent.com/13171924/107992243-49e60e00-6fa6-11eb-9294-6037a1f2e2ce.png)

**Comment by foreverphoenix** [comment]
Yup, fixed in 4.2
