### ISSUE TITLE
Stone of Barenziah missing from Proudspire Manor

### ISSUE THREAD

**Issue by Dathide** [foreverphoenix/the-phoenix-flavour#128]
After purchasing Proudspire Manor and all decorations, the Stone of Barenziah isn't in the master bedroom like it is supposed to be.

Edit: I tried waiting for 10 days in a separate cell to see if it would spawn, but it did not.

Edit2: This is the spot I am checking (from elderscrolls.fandom.com):
![image](https://user-images.githubusercontent.com/47128084/108275796-189b4880-7134-11eb-960c-a95b93b7687a.png)

Edit3: I had to manually give myself the stone and fix the quest with these commands:
set TGCrownGemsFound to 24
set TGCrownGemsTotal to 24
setstage TGCrown 30

**Comment by foreverphoenix** [comment]
No this isn't a bug. The stone was moved, the Solstheim. It's done by [this mod](https://www.nexusmods.com/skyrimspecialedition/mods/27939?tab=files) and documented [in the gameplay guide](https://thephoenixflavour.com/skyrim-se/gameplay-guide/quests/#no-stone-unturned).
