### ISSUE TITLE
rude imperial soldiers escort already ported

### ISSUE THREAD

**Issue by thefinition** [foreverphoenix/the-phoenix-flavour#131]
a pinned comment under [Rude Imperial Soldiers Escort Prisoner fix ](https://www.nexusmods.com/skyrimspecialedition/mods/894)
redirects user to [this](https://www.nexusmods.com/skyrimspecialedition/mods/32332) nifty patches repository that already has the .esp eslfied and ported to form 44 :-)

**Comment by foreverphoenix** [comment]
Excellent, added it for the next update. Thanks!
