### ISSUE TITLE
Mod Suggestions: Ancient AMidianborn Dwarven Armor & Patches for SMIM

### ISSUE THREAD

**Issue by Aeroscorp** [foreverphoenix/the-phoenix-flavour#137]
I thought either of these would be awesome to maintain visual consistency with the Dwemer ruins.

https://www.nexusmods.com/skyrimspecialedition/mods/38316

https://www.nexusmods.com/skyrimspecialedition/mods/38845

**Comment by foreverphoenix** [comment]
Both added in the 4.4 update. Thanks!
