### ISSUE TITLE
Corpses Stretching in Ruins

### ISSUE THREAD

**Issue by Foamimi** [foreverphoenix/the-phoenix-flavour#143]
Hello! I just started a new playthrough and haven't gotten to the point where I become the Dragonborn yet. I headed over to Bleakfalls Burrow to participate in obtaining the Dragonstone tablet when I noticed this mangled corpse in the room where you fight the Large Frostbite Spider. 

![SkyrimSE 2021-02-26 01-10-36](https://user-images.githubusercontent.com/37861844/109270464-ad0c4780-77d3-11eb-8b83-8f7a2a5d243e.png)
![SkyrimSE 2021-02-26 01-10-45](https://user-images.githubusercontent.com/37861844/109270466-ae3d7480-77d3-11eb-8cb2-1d2913c004b5.png)
![SkyrimSE 2021-02-26 01-28-40](https://user-images.githubusercontent.com/37861844/109270469-ae3d7480-77d3-11eb-9d52-b578427826e4.png)
![SkyrimSE 2021-02-26 01-29-10](https://user-images.githubusercontent.com/37861844/109270470-aed60b00-77d3-11eb-9588-68735a56653c.png)

If it helps at all, I've installed the guide various times manually over the past year and a half, however, this was my first time taking the Wabbajack route. I also do not have any off-guide mods installed. 

Thanks, and lovely guide! <3

**Comment by foreverphoenix** [comment]
It's a vanilla issue according to Lively. I am not certain how much certain meshes in TPF may contribute to this occuring. Leaving those open for further reports!
