### ISSUE TITLE
Glow Be Gone - GhostFX Workaround not doing it's job!

### ISSUE THREAD

**Issue by caiobraz** [foreverphoenix/the-phoenix-flavour#147]
I've pinged you on #tpf-wabbajack-support for context, user Aix reported

Those ghost summons are TOO GHOSTY :P
![20210228011243_1](https://user-images.githubusercontent.com/6069263/109407804-bd066180-7962-11eb-9737-0bb3810dc865.jpg)

**Comment by foreverphoenix** [comment]
Yup, not covered by GhostFX workaround plugin. Will check if I can fix this.

**Comment by foreverphoenix** [comment]
Glow Be Gone was ultimately removed.
