### ISSUE TITLE
Suggested Clarification for Enabling enblocal.ini Settings in ENB Man

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#148]
Current text from https://thephoenixflavour.com/skyrim-se/finalisation/enbseries/:

> Double-click the enblocal.ini inside to import it and check all boxes.

Suggested change:

> Double-click the enblocal.ini inside to import it, press Ctrl + A to select all settings, and click the green checkmark button in the toolbar to enable all selections.

If you have the source Jekyll files in a repo somewhere, I'll open future issues like this as merge requests against the files directly.

**Comment by foreverphoenix** [comment]
> If you have the source Jekyll files in a repo somewhere, I'll open future issues like this as merge requests against the files directly.

It's Hugo+Docsy actually, and the files are in the content folder. I much prefer issue reports over PRs though!
Will implement your suggestion in the next update.

**Comment by foreverphoenix** [comment]
Added in 4.4.1
