### ISSUE TITLE
Corrected Instructions for Deleting Textures for HD Dead Trees and Driftwoods

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#149]
Currently the paths are:

- textures\Spooknik\reachtreebranch01.dds
- textures\Spooknik\reachtreebranch01_n.dds

But they should be:

- textures\Spooknik\landscape\trees\reachtreebranch01.dds
- textures\Spooknik\landscape\trees\reachtreebranch01_n.dds

**Comment by foreverphoenix** [comment]
Thanks, fixed for the next update. =)
