### ISSUE TITLE
Imperial Portcullis broken texture

### ISSUE THREAD

**Issue by Umgak** [foreverphoenix/the-phoenix-flavour#15]
![image](https://user-images.githubusercontent.com/40526330/80630901-8b5afc00-8a1a-11ea-86b3-a8cbb39697d9.png)
Ruins Clutter Improved changes the UV Map for the imperial portcullises, but Underground - a dungeon texture overhaul overwrites its textures with ones which expect the vanilla UV Map.
Delete the following files from Underground - a dungeon texture overhaul
`\textures\dungeons\imperial\impwooddoorsingle01.dds`
`\textures\dungeons\imperial\impwooddoorsingle01_n.dds`

**Comment by foreverphoenix** [comment]
Fixed.
