### ISSUE TITLE
All files from SD’s Farmhouse Fences Version 2 Deffuse are Redundant

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#151]
2k Slightly Desaturated Version 2 Deffuse provides the following:
  📁 textures
    📁 Sdlutz Custom Fences
      📄 Fences001.dds (2.8 MB)
      📄 Fences002.dds (2.8 MB)
      📄 Fences003.dds (2.8 MB)

But the mod listed after that, True Nordic Farmhouses - SD’s Farmhouse Fences Texture Patch, provides the same files in the directory instructed in the list:
📁 textures
  📁 Sdlutz Custom Fences
    📄 Fences001.dds (5.6 MB)
    📄 Fences002.dds (5.6 MB)
    📄 Fences003.dds (5.6 MB)

Thus, this line can just be dropped from the instructions:
> Optional Files: 2k Slightly Desaturated Version 2 Deffuse » merge with the main file

**Comment by foreverphoenix** [comment]
Ouch, I missed that. Thanks! Fixed in 4.4
