### ISSUE TITLE
Blood on The Ice Quest - CTD when completing, every time

### ISSUE THREAD

**Issue by dimebag28** [foreverphoenix/the-phoenix-flavour#16]
I'm aware that this vanilla quest (Blood on the Ice) is plagued with issues not related to this mod guide but after running the phoenix mod guide (3.0 & 3.2) with fantastic results with no CTD's at any point, with 100 hours of solid gameplay & testing, I cannot complete the Blood On the Ice quest without the game CTD'ing every single time i speak to Jorleif at the end. Can avoid crashes by just not completing the quest but would be great if this could be fixed somehow. Checking the logs around the CTD there are a lot of Relationship Dialogue Overhaul lines in the transcript just before the CTD. Not sure if this is a contributor to the crashes or not.

**Comment by foreverphoenix** [comment]
[Finding Susanna Alive](https://www.nexusmods.com/skyrimspecialedition/mods/32512) which directly overhauls Blood on the Ice doesn't have any crash reports so this CTD is probably the result of a conflict of some sort. I'll look into it. Could you upload the crash log?

**Comment by caiobraz** [comment]
I played through the quest, tried all outcomes (i.e. arresting and not arresting Wuunferth) and in both cases, I had no issues at all, everything played out as it should be.

**Comment by foreverphoenix** [comment]
Could both of you share your modwatch links please? I'd like to see which optionals you skipped.

**Comment by caiobraz** [comment]
https://modwat.ch/u/sr_kaio/plugins

**Comment by dimebag28** [comment]
Sorry for the delayed response.

False alarm.

2 fuck ups - I hadnt downloaded the latest load order file from discord and I had also somehow disabled the USSEP plugin too without realising (It's the only plugin that doesnt come up as a warning when you load a save without it enabled), like an idiot.

Have run through the quest several times since reenabling and no CTD.

As I had previously said, I was surprised to have a ctd when the phoenix guide has given me such a stable and enjoyable game over several iterations, I should have known it wouldnt have been the cause!

Apologies, and thanks for the quick response, and care for solving the issue even if it was just stupid user error.

Dimebag28





________________________________

**Comment by foreverphoenix** [comment]
Glad you got it sorted. =)
