### ISSUE TITLE
Skip Loading Refs in SSEEdit When Not Needed

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#162]
For steps such as those outlined in https://thephoenixflavour.com/skyrim-se/mod-installation/apparel-weapons/#gemling-queen-jewelryhttpswwwnexusmodscomskyrimspecialeditionmods4294tabfiles, we should instruct users to hold down shift when confirming the plugin selection. Not loading references saves time, especially on slower PCs.

**Comment by tohuw** [comment]
While I realize a cache gets built up that speeds up references, I don't think that gain is significant enough to make it worth loading refs for quick edits like these. But it's not a big deal either way. Whatever you think balances ease with optimization.

**Comment by foreverphoenix** [comment]
It saves about 7 seconds of time when loading the whole plugin list which I don't think is worth it.
