### ISSUE TITLE
Link Directly to Files Section for SKSE INI

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#163]
https://thephoenixflavour.com/skyrim-se/initial-setup/skyrim-script-extender/#skse-ini should link to https://www.nexusmods.com/skyrimspecialedition/mods/1651?tab=files to be consistent with the convenience throughout the guide of linking directly to the files section of mods.

**Comment by foreverphoenix** [comment]
Yup that's fair. Changed in the next update.

**Comment by foreverphoenix** [comment]
Fixed in 4.4.3
