### ISSUE TITLE
Dummy Plugin to Load Correct zEdit Selections for Facegen?

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#167]
How about a dummy plugin to drop in for pre-selecting the correct mods to activate in zEdit? It could be added in just for that step, with an instruction to deactivate it later. This would save users from having to scroll through the (non-searchable) list to find the right mods: they'd just select the dummy plugin that would have the correct mods as masters, then de-select the dummy itself.

That does add a maintenance step for you if Facegen instructions change. If you find that cumbersome, I'm happy to maintain the dummy plugin and make it a mod people can download from the Nexus for that step. Just let me know.

**Comment by foreverphoenix** [comment]
It would be easier to just provide the NPCsWithFaces.esp to begin with. I don't necessarily want to do that since the point is also to show people the full process of recreating facegen. I'll think about it though.

**Comment by tohuw** [comment]
Sure, that makes sense. I wonder if it might be best to create an xEdit script that will detect the correct plugins to select and build a plugin from that. This would solve the convenience issue of having to search through zEdit’s list of plugins, and also ensure the right plugins are always selected for Facegen. I’ll tinker with a script that has a similar purpose and see if I can come up with a good proposal here.

 

Conversely, the zEdit script could be converted to an xEdit script, but that’s a bit outside my wheelhouse.

**Comment by foreverphoenix** [comment]
No longer relevant since facegen is now pre-made.
