### ISSUE TITLE
Time Format Changer [SKSE plugin]

### ISSUE THREAD

**Issue by thefinition** [foreverphoenix/the-phoenix-flavour#172]
an awesome skse plugin that changes the time formatting in waiting tab (T), on Tab menu and anywhere I could fine time shown
very useful if youre not American, we dont use AM / PM in Europe (sorry, no idea about other parts of the world), 3 PM for us is 15:00 while 3 AM is 03:00 and it takes some brain thinking process to convert AM / PM to "our" time even after tens of years learning english :D
https://www.nexusmods.com/skyrimspecialedition/mods/28921
the fomod installer includes many custom presets, it also allows to to make one yourself, very enjoyable little mod

**Comment by foreverphoenix** [comment]
This is part of TPF-X now.
