### ISSUE TITLE
Storm Lightning is Now Pre-Configured with Ultra Realistic Preset

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#173]
https://thephoenixflavour.com/skyrim-se/mod-configuration/#storm-lightning advises a need to change the preset, however as of 1.4.6, this change was implemented:

> Adjusted preset settings. The mod comes with Ultra Realistic preset settings as default now, so no insane lightning storms on new game. Also lowered Realistic preset frequency to make it actually realistic. Adjusted highest preset settings accordingly.

Thus, I suggest we drop this configuration step entirely.

**Comment by foreverphoenix** [comment]
I missed that somehow. Thanks! Will be implemented in the next update.

**Comment by foreverphoenix** [comment]
Fixed in 4.4.3
