### ISSUE TITLE
Remove "Bless Home" Power

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#174]
We should patch out the Bless Home power added by Hearthfire Multiple Adoptions; it isn't needed for TPF as there are no custom homes included or supported.

This should ideally be done in its own patch so that it can be dropped if someone chooses to self-install custom homes or uses an addon that includes them.

**Comment by foreverphoenix** [comment]
Yeah I know, it's on my To Do list already.

**Comment by foreverphoenix** [comment]
Done in 4.4.3
