### ISSUE TITLE
[MOD SUGGESTION] Steam-Driven Automatons (Very Simple, Lore-Appropriate Change)

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#175]
The author of the mod says it best:

> Dwarven Automatons resistances have been swapped. 
> Original resistances: 25% Resist Magic, 100% Resist Frost, 100% Resist Poison.
> New resistances: 25% Resist Magic, 50% Weakness to Frost, 100% Resist Poison.
> The book "Ruins of Kemel-Ze" imply they are weak to Frost. Just a simple, uncomplicated swap with no extra frills.

https://www.nexusmods.com/skyrimspecialedition/mods/40225

**Comment by foreverphoenix** [comment]
Oh yeah I liked this, have it on my list somewhere.

**Comment by foreverphoenix** [comment]
Added in 4.5
