### ISSUE TITLE
Use kryptopyr's patch for CCOR & JS Circlet Replacer (was: Mod suggestion: Circlet USSEP Fixes)

### ISSUE THREAD

**Issue by WilliamImm** [foreverphoenix/the-phoenix-flavour#18]
**EDIT:** See [updated comment](https://github.com/foreverphoenix/the-phoenix-flavour/issues/18#issuecomment-624223782) - short verison, since CCOR is mandatory & replaces circlet models anyway, JS Circlet Replacer users should [use the patch from Kryptopyr's patch hub](https://www.nexusmods.com/skyrimspecialedition/mods/19518?).

---

[Circlet USSEP Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/35576) - originally suggested by GuybrushPluto on the Discord, looks to be a good idea. USSEP replaces the circlet mesh for females elves, which takes priority over JS's mesh in that specific case. This resolves that.

For The Phoenix Replacer, install the "JS Circlet Replacer USSEP Fix" main file, if and only if JS Circlet Replacer is also installed.

**Comment by foreverphoenix** [comment]
Will do.

**Comment by WilliamImm** [comment]
As suggested in the Discord (don't remember did this first), [kryptopyr's patch hub](https://www.nexusmods.com/skyrimspecialedition/mods/19518) has a patch that lets all the circlets that CCOR uses & all vanilla circlets modified by it use the JS Circlet Replacer model. This should be used in place of Circlet USSEP fixes if JS Circlet Replacer is used

This does mean that the new circlets added in by CCOR will still use the vanilla circlet models, if that bothers users Krypto suggets disabling "More Jewlery" in the CCOR MCM.

**Comment by foreverphoenix** [comment]
Added in 3.2 Beta 7.
