### ISSUE TITLE
Canticle Tree Bark - Missing from Changelog

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#181]
https://thephoenixflavour.com/tpf/mod-installation/trees-plants/#canticle-tree-and-barkhttpswwwnexusmodscomskyrimspecialeditionmods45548tabfiles

**Comment by foreverphoenix** [comment]
Yeah I know, already fixed for the next update. =)

**Comment by foreverphoenix** [comment]
Fixed in 4.4.3
