### ISSUE TITLE
[Guide Suggestion] MO2 FNIS Plugin Removal

### ISSUE THREAD

**Issue by Kravarnik** [foreverphoenix/the-phoenix-flavour#187]
Since the guide is not using FNIS anymore I think it would be a great idea to remove the FNIS related plugins from MO2 just to keep everything even more neat and clean, I have removed those 4 files as seen in the image below:
![image](https://user-images.githubusercontent.com/21342211/110730753-b5c83900-8229-11eb-9ab4-c741a86f0f63.png)

and basically that cleans the tools section:
![image](https://user-images.githubusercontent.com/21342211/110730502-3b97b480-8229-11eb-98a8-ec8e86dd3ee4.png)

From what I've tested so far, MO2 behavior seems to be normal.

**Comment by tohuw** [comment]
I think this might create unnecessary confusion if users choose to create a non-TPF profile that relies upon FNIS. There's a ton of files in the MO2 folder; I don't think people will get too hung up about 4 extras.

**Comment by Kravarnik** [comment]
I didn't think about that actually. Good point!

**Comment by foreverphoenix** [comment]
I don't think this is necessary either tbh.
