### ISSUE TITLE
aMidianBorn Content Addon – Plugin Replacer missing

### ISSUE THREAD

**Issue by torquadon** [foreverphoenix/the-phoenix-flavour#19]
35.5 aMidianBorn Content Addon – Plugin Replacer seems to be missing on the page link directs to.

**Comment by WilliamImm** [comment]
Not a bug. The plugin is currently in development on the original mod author's end. Discord server has the plugin replacer.

**Comment by foreverphoenix** [comment]
I clarified the instructions in Beta 6.
