### ISSUE TITLE
SSELODGen Occlusion Overwrites RWT Waterflow Data

### ISSUE THREAD

**Issue by tohuw** [foreverphoenix/the-phoenix-flavour#191]
Realistic Water Two has a specific XCWT for Worldspace `9098`, but Occlusion clobbers this.

I haven't looked in-world to see how noticeable this overwrite is.

**Comment by foreverphoenix** [comment]
xLODGen will forward any edits that are last in the load order. I had this problem as well once but it turned out I'd messed up somehow (probably forgot to enable the CRP to forward those water records) and it fixed itself.

**Comment by tohuw** [comment]
Oh, I must have screwed something up then. I'll re-check. Sorry!
