### ISSUE TITLE
mismatched wolf armor

### ISSUE THREAD

**Issue by butttthead** [foreverphoenix/the-phoenix-flavour#196]
![ScreenShot24](https://user-images.githubusercontent.com/80812764/111940449-02164300-8a8c-11eb-8dec-20356e90f392.png)
wolf helm doesn't match the rest of the set. looks like its made out of steel

**Comment by foreverphoenix** [comment]
This should no longer be an issue since we are using OWL AVL. The white fur variant (from the screenshot here) is a shade darker than the brown/black variants. Unfortunately, here isn't a matching helmet and so I didn't include the Nordic White variant in OWL AVL to begin with.
