### ISSUE TITLE
WJ: Frankly HD Miraak 2K - Bad installation

### ISSUE THREAD

**Issue by caiobraz** [foreverphoenix/the-phoenix-flavour#197]
Apparently, it was just an oversight, manual guide is correct, but apparently the WJ version you didn't merged the patch, but replaced the original mod, thus having only a single mesh in it.

Here for context: https://discord.com/channels/458216677792808961/698967002282197032/824746562243526666

**Comment by foreverphoenix** [comment]
Fixed in 4.5
