### ISSUE TITLE
Visceral ENB causes white shimmering around edges.

### ISSUE THREAD

**Issue by foreverphoenix** [foreverphoenix/the-phoenix-flavour#2]
This is a known issue. MD has been working on an update for Visceral but there hasn't been any news about that for a while. If someone knows what to tweak about the ENB to get rid of the shimmering, let me know. Toning down AO intensity helps at least.

**Comment by dimebag28** [comment]
Not a complete fix, but after a lot of tweaking i got fed up and changed grass to Veydosebrom which has all but removed the shimmering. I imagine it is not as fps friendly if you have a low end rig but i have had no drop in fps in my game and it seems to work better with the Visceral ENB.

**Comment by foreverphoenix** [comment]
Haven't been using Visceral for sometime now.
