### ISSUE TITLE
Potential Visual Bugs with 4.5.1, see images

### ISSUE THREAD

**Issue by JustWyvern** [foreverphoenix/the-phoenix-flavour#212]
**1.** Hair looking pretty out of place, either the color is just off or it gets full lighting for some reason.
![489830_20210410070928_1](https://user-images.githubusercontent.com/82341984/114321606-4f149480-9ae1-11eb-87eb-d78dd0928a11.png)

**2.** Blacksmith Forge Water in Riften looks like the texture gave up existing for a large portion of it. RW2 Bug?
![489830_20210411154751_1](https://user-images.githubusercontent.com/82341984/114321662-86834100-9ae1-11eb-9d74-3406a08f818f.png)

This is all I've seen so far, other than a very slight motion blur that makes my eyes not like my screen after a long while (which I cannot screenshot, so I think it has to do with fps/monitor refresh rate? I average 71 fps with a 144hz 1080p MSI Optix MAG241C curved screen monitor). Assistance is appreciated.

**Comment by caiobraz** [comment]
Just to confirm:
I could repro both on Pure TPF from WJ

first one, is apparently an ENB casted shadow, i couldn't see it turning the ENB off

second one is present, prolly a lingering edit on position regarding JK's Lite cities, maybe there are other, good to check!

**Comment by foreverphoenix** [comment]
Skyrim doesn't really have motion blur but TXAA can cause a similar effect. You can disable it and enabled FXAA instead but it won't look as good. I personally don't notice any blur playing capped at 60FPS.

The hair is just the retexture which looks a bit smoother than vanilla. The currently available hair mesh replacers have too many issues to be considered for inclusion at the moment. Other than that I've been meaning to experiment with the ENB fix black hair setting which may affect this.

And I'll check the water trough. Should be easy to fix.
