### ISSUE TITLE
Remove unofficial performance optimized textures

### ISSUE THREAD

**Issue by WilliamImm** [foreverphoenix/the-phoenix-flavour#22]
There's little to no practical benefit or percivable difference with this mod when it is installed under Mod Organizer. The only difference this would make is in filesize compared to the original BSAs, which is irrelevant in the case of MO users.

**Comment by LivelyDismay** [comment]
Seconded.

**Comment by foreverphoenix** [comment]
Done in 3.2 Beta 6.
