### ISSUE TITLE
[Mod Suggestion] Haunting and Mourning

### ISSUE THREAD

**Issue by Lexileile** [foreverphoenix/the-phoenix-flavour#220]
https://www.nexusmods.com/skyrimspecialedition/mods/33277?tab=description

>  This mod restores a couple of world interaction events that Bethesda left disabled on purpose: "Haunting" and "Mourning". These both happen when an unique NPC dies.

**Comment by foreverphoenix** [comment]
Mod was removed from the Nexus.
