### ISSUE TITLE
[Mod suggestion] VHR - Vanilla Hair Replacer

### ISSUE THREAD

**Issue by Aelthor** [foreverphoenix/the-phoenix-flavour#224]
https://www.nexusmods.com/skyrimspecialedition/mods/25574

VHR is a lore-friendly hair replacer that tries to stay true to the vanilla hairstyles with high-poly replacements. Made for men and mer.

I have done the facegen process with this mod and the results are imho very good. I think some vanilla hair are ugly and this mod replace them keeping them lore-friendly, realistic, natural both in shape and color. 

I suggest this mod cause i think it would be a big nice improvement to characters'appearance without changing vanilla+ TPF spirit. 
![VHR - example comparison](https://user-images.githubusercontent.com/82775494/115156735-0e3ef180-a086-11eb-8f7f-6b12d6ac2e10.jpg)

**Comment by foreverphoenix** [comment]
Yeah I know the mod, I wasn't a fan honestly. Maybe I'll take a closer look one day but from the screenshots I'm not convinced.

**Comment by owopeachy** [comment]
> https://www.nexusmods.com/skyrimspecialedition/mods/25574
> 
> VHR is a lore-friendly hair replacer that tries to stay true to the vanilla hairstyles with high-poly replacements. Made for men and mer.
> 
> I have done the facegen process with this mod and the results are imho very good. I think some vanilla hair are ugly and this mod replace them keeping them lore-friendly, realistic, natural both in shape and color.
> 
> I suggest this mod cause i think it would be a big nice improvement to characters'appearance without changing vanilla+ TPF spirit. ![VHR - example comparison](https://user-images.githubusercontent.com/82775494/115156735-0e3ef180-a086-11eb-8f7f-6b12d6ac2e10.jpg)

please can you outline how you did the face gen here, I am struggling because i want to use it but it always makes all the faces black and i can't use creation kit because despite running it through MO it doesnt pick up any of the mods i have loaded...
