### ISSUE TITLE
Waking Dreams + Enhanced Reanimation bug

### ISSUE THREAD

**Issue by caiobraz** [foreverphoenix/the-phoenix-flavour#227]
![image](https://user-images.githubusercontent.com/6069263/116008544-860f9d80-a5eb-11eb-986b-de9fd6c48f2c.png)

Link to [Keizaal issue](https://github.com/PierreDespereaux/Keizaal/issues/148)

But apparently, there's a fix:
https://forums.nexusmods.com/index.php?/topic/9416193-reanimation-skse-plugin/page-6#entry90160808

**Comment by caiobraz** [comment]
Confirmed: the fix above works, it's not needed to yeet the mod as Pierre did

Apparently that line is avoiding Miraak to ride his dragon, therefore, the cutscene stalls

**Comment by caiobraz** [comment]
The mod itself updated to fix this bug :)

**Comment by foreverphoenix** [comment]
Confirmed, will be updated for WJ in 4.6
