### ISSUE TITLE
[Guide - Minor] No version requirement for Essential Favourites

### ISSUE THREAD

**Issue by x-Slim** [foreverphoenix/the-phoenix-flavour#228]
Due to an update on [Essential Favourites](https://thephoenixflavour.com/tpf/mod-installation/assorted-plugins/#essential-favoriteshttpswwwnexusmodscomskyrimspecialeditionmods42997tabfiles) (2.1), there is no longer a .ini file supplied with the mod but generates when the game is run.

Either some updated instructions are needed or just need to specify to download version 2.0.

No fancy format this time :c

**Comment by foreverphoenix** [comment]
Fixed in my current dev version of 4.6 =)
