### ISSUE TITLE
[Mod Suggestion] Convenient Reading UI - SE

### ISSUE THREAD

**Issue by sneaky-witch-thief** [foreverphoenix/the-phoenix-flavour#233]
[Link to the mod](https://www.nexusmods.com/skyrimspecialedition/mods/50202)

FEATURES (from the mod description)
- Adjusted book position on the screen
- Faster book opening animation
- Faster page turn animations
- Configurable book/note font size
- Configurable bottom bar elements
- Compatible with any font replacer
- No more laser-printed book integrated
- No scripts or DLLs

**Comment by foreverphoenix** [comment]
Yup, added in 4.6 =)
