### ISSUE TITLE
Skyrim Remastered - Azura and Blackreach Crystals vs. Iconic's Blackreach Crystals Retexture

### ISSUE THREAD

**Issue by Heartbreaker714** [foreverphoenix/the-phoenix-flavour#237]
You may want to check out [Skyrim Remastered - Azura and Blackreach Crystals](https://www.nexusmods.com/skyrimspecialedition/mods/38371) . I tried it on a fluke but when I compared it to [Iconic's Blackreach Crystals Retexture](https://www.nexusmods.com/skyrimspecialedition/mods/45917), I gotta admit it really looks a lot better in-game

Anyhow something to consider chancking out

**Comment by foreverphoenix** [comment]
Yup, I like it to. Add in 4.6!
