### ISSUE TITLE
[Mod Suggestion] Reforging - To the Masses (Weapons Expansion)

### ISSUE THREAD

**Issue by pyragius** [foreverphoenix/the-phoenix-flavour#253]
`RFM adds around 300 vanilla-friendly weapons to the game. Made by registrant.`
Has Open World Loot patch as both mods are made by the same creator.
https://www.nexusmods.com/skyrimspecialedition/mods/49030

**Comment by foreverphoenix** [comment]
From the screenshots, I'm really not impressed. The mod looks like it's mostly made to have a big number. I'd rather have fewer but higher quality new assets. This is not the kind of mods I'd be interested in.
