### ISSUE TITLE
The AllGUD Alternate Texture script doesn't copy the texture paths the right way

### ISSUE THREAD

**Issue by duskyBabz** [foreverphoenix/the-phoenix-flavour#26]
I reported it to the mod author but they haven't been active on the nexus for over a month so I'm leaving this here as well.

The script copies those paths based on the order that they are presented in xedit which is not how the textures are actually loaded.
The generated meshes have texture paths set up like this: https://i.imgur.com/osvmRa4.png
They should be like this: https://i.imgur.com/IkFwzOm.png

You can see that while the resulting items don't really look bugged (since the diffuse and normal paths are still correct), they don't look quite as intended

It is a simple fix, the order of the texture paths just needs to be changed slightly.
I have a fixed script here: https://www.mediafire.com/file/fd0d6qj78lpjbas/AllGUD_AlternateTextureModelsplosion_-_Fixed.pas/file

**Comment by foreverphoenix** [comment]
Hey, apologies for my very late response and massive thanks for providing the fixed script! I will be including it in the next version of the guide. Would you be willing to let us upload it to our patch hub on the Nexus for ease of use?

**Comment by duskyBabz** [comment]
Sure, do as you please!

**Comment by foreverphoenix** [comment]
Thanks! It's linked in the guide now and I'll put it on the Nexus when I can. =)
