### ISSUE TITLE
Alchemy table unable to be interacted with

### ISSUE THREAD

**Issue by tomuuu** [foreverphoenix/the-phoenix-flavour#260]
On my current playthrough I've only been able to interact with one alchemy table, every other one I can't use, I've also forgotten which was the one that worked.  Shouting, using spells etc doesn't change anything. Reloading saves doesn't.

Installation through wabbajack. 

![image](https://user-images.githubusercontent.com/7601713/126235706-92dbd6ab-e4f3-4e6e-9800-591b81973e61.png)
![image](https://user-images.githubusercontent.com/7601713/126235765-47df2af1-5bcc-4f82-9784-a51cdfe271cd.png)

**Comment by foreverphoenix** [comment]
Fixed in TPF 4.6.2
