### ISSUE TITLE
Mod "No Heavy Muscular Walk and Idle" under Skyrim SE is showing not found

### ISSUE THREAD

**Issue by icdcom** [foreverphoenix/the-phoenix-flavour#261]
The link to the "No Heavy Muscular Walk and Idle" under Skyrim SE is showing not found, is the mod "No heavy muscular idle" under the Skyrim section a good replacer?
![Screenshot 2021-07-20 214957](https://user-images.githubusercontent.com/1094693/126335587-b77b9a48-a4c3-459f-a4dc-617908920489.png)
![Screenshot 2021-07-20 215053](https://user-images.githubusercontent.com/1094693/126335738-3da9d619-ffe5-4f7c-a32e-d4f5ed52a058.png)

**Comment by YuyanguY** [comment]
I installed it and resaved the plugin with creation kit, I think it's working fine for me in game

**Comment by foreverphoenix** [comment]
Yeah the SSE port was taken down, we are now using the original.
