### ISSUE TITLE
[MOD SUGGESTION] Dirt and Blood 

### ISSUE THREAD

**Issue by YuyanguY** [foreverphoenix/the-phoenix-flavour#262]
https://www.nexusmods.com/skyrimspecialedition/mods/38886
Nice visual fx, light weight, no conflict with anything when I checked in SSEEdit. Can be a little bit intrusive - you look unbearably dirty after a day or two and you need to swim/shower, adds a "wash and rinse" shout. Customisable through MCM.

**Comment by foreverphoenix** [comment]
Not a mod for TPF
