### ISSUE TITLE
[Mod Suggestion] Ivy and Hanging Moss by Mari

### ISSUE THREAD

**Issue by cturko** [foreverphoenix/the-phoenix-flavour#263]
https://www.nexusmods.com/skyrimspecialedition/mods/37112
https://www.nexusmods.com/skyrimspecialedition/mods/34772

The one change I made to my TPF installation was to substitute the recommended Rally's ivy and hanging moss with Mari's (see link above).

When I was performance testing, I found that the hanging moss and ivy in particular appeared over-saturated in the LOD in most daytime lighting. The contrast was most noticeable when the ivy/moss was hanging from farmhouses, wooden buildings, and stone walls. 

The colour palette of Rally's is seamless with Veydosebrom, so it definitely is a matter of personal preference.

I don't have any specific side-by-side comparisons since I never intended to submit a suggestion. But I can share two screenshots of my TPF installation showing the Mari ivy textures:

https://steamcommunity.com/sharedfiles/filedetails/?id=2560988107
https://steamcommunity.com/sharedfiles/filedetails/?id=2560986731

Thanks again for the guide and all of your hard work!

**Comment by foreverphoenix** [comment]
Ivy by Mari is now part of TPF. Not sure about the moss yet.
