### ISSUE TITLE
Dialogue Subtitles Stuck After Ending Conversation

### ISSUE THREAD

**Issue by Aeroscorp** [foreverphoenix/the-phoenix-flavour#41]
SkyHUD appears to be the culprit.

When exiting a conversation with a NPC, sometimes their first line of dialogue will remain on-screen. This is usually seen when exiting a vendor screen or when someone from 3DNPCs exits dialogue and continues it while moving around.

A screenshot is included to demonstrate this in Whiterun Market.
![34523792-D42A-4F4E-B65D-021B0F35E401](https://user-images.githubusercontent.com/19329511/83932308-4c317080-a767-11ea-8f05-feea188135c2.jpeg)

If this were from outside a conversation, then the subtitle would indicate the speaker. As it is, it appears as if you have just entered dialogue - yet, you are not.

**Update: The problem is _not_ SkyHUD. Here is a pic of a stuck piece of dialogue with SkyHUD disabled.**

![enb2020_6_5_20_26_07](https://user-images.githubusercontent.com/19329511/83933086-3160fb00-a76b-11ea-8c73-dca221aa3e76.jpg)

**Comment by D1Z4STR** [comment]
This happens to me randomly as well in Riverwood (starting on vanilla start). No idea what causes it.

**Comment by caligineux** [comment]
This is a known issue with Fuz Ro D-oh. https://www.nexusmods.com/skyrimspecialedition/mods/15109?tab=bugs

**Comment by foreverphoenix** [comment]
Ahhh I see, that is good to know. Thank you! I will close the issue then and add the info to a Known Issue list on the website.
