### ISSUE TITLE
Mistitled separators

### ISSUE THREAD

**Issue by x-Slim** [foreverphoenix/the-phoenix-flavour#55]
Just a copy of what I posted in #feedback on Discord

Current separators file on nexus has separator 34 as **34 New Encounters & Enemies** rather than **34 New Encounters & Creatures**  and separator 39 as **39 Enb Particles** rather than **39 Skeleton & Animations**

**34 New Encounters & Enemies** >>> **34 New Encounters & Creatures**
**39 Enb Particles** >>> **39 Skeleton & Animations**

Rest of the separators looked fine

**Comment by foreverphoenix** [comment]
Should be all fixed now!
