### ISSUE TITLE
Invisible Necromancer's Amulet

### ISSUE THREAD

**Issue by caligineux** [foreverphoenix/the-phoenix-flavour#59]
The Necromancer's Amulet appears invisible in game due to Complete Crafting Overhaul Remastered 2.2 not packing the custom mesh nor textures for it into the bsa. I suppose the easiest fix is to create an override record that reverts the mesh back to the original, but you could alternatively acquire the missing mesh and textures from Complete Crafting Overhaul Remade 1.7 over at Skyrim LE Nexus.

**Comment by foreverphoenix** [comment]
Confirmed. Will revert texture path in the CRP for the next TPF update (3.5). Thanks a lot for reporting this issue!
