### ISSUE TITLE
Gilded and Silvered Ebony Armor texture mismatch

### ISSUE THREAD

**Issue by Shadowon011** [foreverphoenix/the-phoenix-flavour#60]
Gilded and Silver Ebony armor looks like in the screenshot if AMB Content Addon compatibility patch from Practical Female Armors is not installed
![enb2020_9_10_01_51_17](https://user-images.githubusercontent.com/49394417/92729665-f5918f00-f372-11ea-99e9-d964300a42ec.png)
![enb2020_9_10_00_40_25](https://user-images.githubusercontent.com/49394417/92729667-f6c2bc00-f372-11ea-8d81-f71580af39ff.png)

**Comment by foreverphoenix** [comment]
Fortunately will no longer be an issue in 4.0
