### ISSUE TITLE
Link broken - High Poly Male Meshes (mod is currently hidden)

### ISSUE THREAD

**Issue by oleg-py** [foreverphoenix/the-phoenix-flavour#70]
In [Appearance](https://thephoenixflavour.com/skyrim-se/mod-installation/23-appearance/) category, link to High Poly Male Meshes - Vanilla plus Seamless Head SSE (https://www.nexusmods.com/skyrimspecialedition/mods/11) is broken as of now.

**Comment by foreverphoenix** [comment]
Back online but will be removed anyway in 4.0
