### ISSUE TITLE
Ethereal Elven Overhaul causes certain beards to clip with faces, even for human races

### ISSUE THREAD

**Issue by duskyBabz** [foreverphoenix/the-phoenix-flavour#8]
Screenshots in [this album](https://imgur.com/a/5OCtib2) illustrate the issue pretty well.
These shots were taken with all mods enabled but I also tested only using SKSE utilities and EEO and the problem is the same. Guide instructions were followed correctly and double checked.

I did some digging and the beard in those first two shots is linked to the "Meshes\Actors\Character\character assets\humanbeardshort15races.tri" file.
I unpacked that file with [this tool](https://www.nexusmods.com/skyrim/mods/30162) to get [these files](https://i.imgur.com/tcYyzqR.png). I did the same for the vanilla file found in the Meshes0 bsa.

While the base .obj file from EEO as well as the files for each human race look exactly the same in Blender as their respective version from vanilla SSE, recreating the beardshumanbeardshort15races.tri with all SSE .obj files but with the EEO .obj files for elf races still fixed the issue for human races.

Of course this is not really any better than simply using the vanilla SSE file as that beard is still broken on elf races, but it confirms where the issue comes from.

To fix the issue completely, in addition to using the vanilla SSE files for the base beard and non-elf races .obj files, the .obj files for elf races will need to be regenerated somehow from the SSE files to fit the EEO elf faces.

I haven't checked at all but it's not impossible that eyebrows and scars could also have issues.

**Comment by duskyBabz** [comment]
Ok so apparently this might not actually come down to an incompatibility with SSE, as it appears humanbeardshort15races.tri from EEO has always been broken. Not sure about the other beards but I expect they have always been faulty as well. I have tried to regenerate tri files with [this tool](https://www.nexusmods.com/oblivion/mods/9360?tab=description) but no luck so far.

For humanbeardshort15 since the mesh is all but identical to the not broken humanbeardshort14, the issue can be fixed by copying beardshumanbeardshort14races.tri from EEO and renaming it to 15.

The issue with [humanbeardshort13](https://i.imgur.com/owbhFQx.png) on elves can be fixed by replacing humanbeardshort13.nif, humanbeardshort13.tri and humanbeardshort13chargen.tri by the files for humanbeardshort12 found in the Meshes0 bsa, and replacing beardshumanbeardshort13races.tri by beardshumanbeardshort12races.tri found in EEO (and renaming them all to 13 of course).
You'll also need to open the new humanbeardshort13.nif and [edit the texture paths to point to the beardshort06 textures](https://i.imgur.com/Ns5vHgQ.png).

It will look slightly different than supposed to though: [before](https://i.imgur.com/zmEJWZs.jpg) / [after](https://i.imgur.com/d4YkFU1.jpg)

Other beards with noticable issues are longer and as such they all have unique models, so I'm afraid they can't be fixed by just swapping files around.

I've uploaded the fixes for those two beards [here](http://www.mediafire.com/file/swtl53mnbzknqpp/Ethereal_Elven_Overhaul_-_Beard_Fixes.7z/file).

Now these are more bandaid fixes than anything, as they don't address the underlying issue that EEO beard tri files seem to have been poorly generated, but I don't know how to redo them completely for now.

**Comment by foreverphoenix** [comment]
Did some testing myself. HumanBeard25 is bugged on Nord and Elves. This is fixed by the tri files you uploaded. Every other beard looks fine for me on humans.

There are some more beards on Elves that are bugged as you said. I'm going to add a Known Issues section to the FAQ with screenshots and an explanation. Since Elves aren't usually bearded, this shouldn't be a major problem for most people.

Ethereal Elven Overhaul has open permissions thankfully. Would it be okay with you if we packaged your TRI files to the guide's CRP?

**Comment by duskyBabz** [comment]
Yes only HumanBeard25 was bugged on humans, the other issues are on elves only.
You can totally include those files in the CRP if you want, feel free to do whatever you need with them.

**Comment by duskyBabz** [comment]
By the way I found [this reddit thread](https://old.reddit.com/r/skyrimmods/comments/d7fmat/mod_release_etheral_elven_overhaul_fixed_beards/) for the release of a mod by MrNeverLost that fixed those very issues with EEO and beards... but the mod is hidden.

I've contacted the author on the Nexus to ask about it, I don't like to do that but I would really like to have access to these fixes

**Comment by foreverphoenix** [comment]
I literally just PM'd him as well. Whoops.

**Comment by duskyBabz** [comment]
Let's hope we can at least get an answer, it's frustrating not knowing why it was hidden

**Comment by duskyBabz** [comment]
[Ahem.](https://i.imgur.com/L80YZ6x.png) Had to do a double take there
Well this is disappointing :/

**Comment by foreverphoenix** [comment]
He replied the same thing to me. I asked him why he would refuse to share files to help others with no cost to himself, very curious to see if I get a response.

**Comment by duskyBabz** [comment]
Replacing humanbeardshort13.tri is actually causing my game to freeze when looking in the direction of what I assume is an NPC that uses that beard.
This is tied to the facial expression morphs that are contained in that tri file but I'm not sure how to go about fixing it, so just remove all 4 files for that beard from the CRP.

Basically only keep humanbeardshort15races.tri, which fixes the one beard that is bugged on human races and is the more important fix. This one is perfectly safe.
Apologies for not testing this sooner.

**Comment by foreverphoenix** [comment]
Hm I only tested this in the AS LAL cell and didn't encounter any freezes with the other files. Though if they aren't part of the HumanBeard25 fix, they are redundant either way. As for the CRP, was pretty sure I copied the right one but might have missed one of Um's update, whoops. Fixing this now.

**Comment by foreverphoenix** [comment]
The [beards fix](https://www.nexusmods.com/skyrimspecialedition/mods/29147) is back up on the Nexus, yay. However, EEO was removed from TPF so it is no longer relevant for us.
