### ISSUE TITLE
Simply Knock Referenced in v4 Clean-Up Page, Not Included in Guide

### ISSUE THREAD

**Issue by Soobrakay** [foreverphoenix/the-phoenix-flavour#83]
Hello!

The Clean-Up page still has references to [Simply Knock](https://thephoenixflavour.com/skyrim-se/finalisation/cleanup/#simply-knock). Just letting you know for consistency since the mod was removed.

**Comment by foreverphoenix** [comment]
Fixed in 4.0 Beta 3
