### ISSUE TITLE
Back of the head is clipping through hoods

### ISSUE THREAD

**Issue by foreverphoenix** [foreverphoenix/the-phoenix-flavour#91]
![Example](https://cdn.discordapp.com/attachments/490889832227143692/805028000587710484/ScreenShot6.png)

**Comment by nihues** [comment]
Hey, I've tested changing head size in racemenu and still same problem, changing hair also don't work (some "no/small hair" style works better, so maybe it's a hair problem).
Happens on all hood types.

**Comment by foreverphoenix** [comment]
It's strange because I couldn't reproduce the issue at all on my end. I tried all loose hoods with different vanilla presets.

**Comment by foreverphoenix** [comment]
Haven't had any reports of this in a long while. Not sure if the issue got inadvertently fixed somehow.
