### ISSUE TITLE
Brief glitch before the carriage ride at the start of the game

### ISSUE THREAD

**Issue by foreverphoenix** [foreverphoenix/the-phoenix-flavour#94]
At the very start of the game, you may be very briefly outside the carriage before being teleported into place. This shouldn't take longer than a second or two and afterward the intro should resume smoothly and glitchfree.

**Comment by Akiral-Spritz** [comment]
Just experienced the glitch starting the game but had an issue where, when rounding the bend in Helgen, the horse gets stuck on a house and permanently walks forward into the house becoming stuck, effectively necessitating a restart

**Comment by foreverphoenix** [comment]
The brief 1-2 second glitch is actually caused by ACC. Will consider a fix or replacement.

**Comment by foreverphoenix** [comment]
Fixed by Umgak's new ACC replacement.
